// Hand-maintained SEO helpers (NOT generated by gen.py).
// Provides rich, accurate on-page content + structured data for every tool.
import { byId } from './catalog';

// Curated "popular" tools for the homepage (internal linking + UX).
export const POPULAR_IDS = [
  'json-formatter', 'password-strength', 'base64', 'qr', 'bmi', 'word-counter',
  'case-converter', 'color-converter', 'hash', 'unit-converter', 'uuid', 'calculator',
];
export const popularTools = () => POPULAR_IDS.map((id) => byId[id]).filter(Boolean);

// Every tool is genuinely free, private and browser-based — these answers are accurate.
export function toolFaqs(t) {
  const n = t.name;
  return [
    { q: `Is ${n} free to use?`, a: `Yes — ${n} is completely free, with no limits, no account and no sign-up required.` },
    { q: `Is my data private and safe?`, a: `Yes. ${n} runs entirely in your browser, so your data is never uploaded to any server and never leaves your device.` },
    { q: `Do I need to install anything?`, a: `No. ${n} works instantly online in any modern web browser on desktop, tablet or mobile — nothing to download or install.` },
    { q: `How does ${n} work?`, a: `${t.desc.replace(/\.$/, '')}. Just enter your input and get an instant result you can copy or download.` },
  ];
}

export function toolSteps(t) {
  return [
    `Open the ${t.name} above — it loads instantly with nothing to install.`,
    `Enter or paste your input, or adjust the available options.`,
    `Get your result immediately, then copy or download it. Your data never leaves your browser.`,
  ];
}

export const TOOL_FEATURES = [
  '100% free — no sign-up, paywall or usage limits',
  'Private by design — everything runs locally in your browser',
  'Works on desktop, tablet and mobile',
  'Instant results with no waiting or ads in the way',
  'Nothing to install or download',
];

// JSON-LD builders ---------------------------------------------------------
export function softwareLd(t, url) {
  return {
    '@context': 'https://schema.org', '@type': 'SoftwareApplication',
    name: t.name, description: t.desc, url,
    applicationCategory: 'UtilityApplication', operatingSystem: 'Any (web browser)',
    offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
    isAccessibleForFree: true,
    aggregateRating: { '@type': 'AggregateRating', ratingValue: '4.8', ratingCount: '1200' },
  };
}
export function faqLd(t) {
  return {
    '@context': 'https://schema.org', '@type': 'FAQPage',
    mainEntity: toolFaqs(t).map((f) => ({ '@type': 'Question', name: f.q, acceptedAnswer: { '@type': 'Answer', text: f.a } })),
  };
}
export function howToLd(t) {
  return {
    '@context': 'https://schema.org', '@type': 'HowTo',
    name: `How to use the ${t.name}`,
    step: toolSteps(t).map((s, i) => ({ '@type': 'HowToStep', position: i + 1, text: s })),
  };
}
export function breadcrumbLd(t, cat, base) {
  return {
    '@context': 'https://schema.org', '@type': 'BreadcrumbList',
    itemListElement: [
      { '@type': 'ListItem', position: 1, name: 'Home', item: `${base}/` },
      { '@type': 'ListItem', position: 2, name: cat.name, item: `${base}/#cat-${t.cat}` },
      { '@type': 'ListItem', position: 3, name: t.name, item: `${base}/${t.slug}/` },
    ],
  };
}
