#!/usr/bin/env python3
"""Extract CSS + tool runtime from the legacy index.html and generate the
Next.js catalog (server-safe metadata) used for routing, SEO and the dashboard."""
import re, json, os, io

ROOT = os.path.dirname(os.path.abspath(__file__))
# Authoring source of truth for all tool implementations (render + init).
# Edit tools here, then re-run `python gen.py` to regenerate lib/ and app/globals.css.
html = io.open(os.path.join(ROOT, 'src', 'tools-source.html'), encoding='utf-8').read()

os.makedirs(os.path.join(ROOT, 'app'), exist_ok=True)
os.makedirs(os.path.join(ROOT, 'lib'), exist_ok=True)

# ---- 1. CSS ---------------------------------------------------------------
css = re.search(r'<style>(.*?)</style>', html, re.S).group(1).strip()

# ---- 2. Inline script (the big no-attribute <script>) ---------------------
core = re.findall(r'<script>(.*?)</script>', html, re.S)[-1]
idx = core.find('NAV + HOME + ROUTER')
cut = core.rfind('/*', 0, idx)
prefix = core[:cut].rstrip()

# Make the runtime importable on the server (no DOM access at module load):
prefix = prefix.replace(
    "const toastEl = $('#toast'); let toastT;",
    "let toastT; function _toast(){ let t=document.getElementById('toast'); if(!t){t=document.createElement('div');t.className='toast';t.id='toast';document.body.appendChild(t);} return t; }")
prefix = prefix.replace(
    "function showToast(msg) { clearTimeout(toastT); toastEl.textContent = msg;",
    "function showToast(msg) { clearTimeout(toastT); const toastEl = _toast(); toastEl.textContent = msg;")
assert "const toastEl = _toast();" in prefix, "toast fix did not apply"

runtime = ("/* AUTO-GENERATED from index.html by gen.py. Edit tools in index.html then re-run. */\n"
           "/* eslint-disable */\n"
           + prefix +
           "\n\n/* ---- module exports for the Next.js tool runner ---- */\n"
           "export function mountTool(el, id){\n"
           "  const t = TOOLS.find(x => x.id === id);\n"
           "  if (!t || !el) return () => {};\n"
           "  el.innerHTML = t.render();\n"
           "  try { if (typeof wireRipples === 'function') wireRipples(el); } catch (e) {}\n"
           "  try { t.init && t.init(el); } catch (e) { console.error('[tool ' + id + ']', e); }\n"
           "  return () => { if (el && el._cleanup) { try { el._cleanup(); } catch (e) {} } };\n"
           "}\n"
           "export { TOOLS, CATEGORIES };\n")

io.open(os.path.join(ROOT, 'app', 'globals.css'), 'w', encoding='utf-8').write(css + '\n')
io.open(os.path.join(ROOT, 'lib', 'runtime.js'), 'w', encoding='utf-8').write(runtime)

# ---- 3. Tool metadata (regex out of the reg({...}) calls) -----------------
tpat = re.compile(
    r"reg\(\{\s*cat:\s*'([^']+)',\s*id:\s*'([^']+)',\s*emoji:\s*'([^']*)',\s*name:\s*'([^']+)',\s*desc:\s*'((?:\\.|[^'\\])*)'",
    re.S)
tools = []
for cat, tid, emoji, name, desc in tpat.findall(core):
    tools.append({'cat': cat, 'id': tid, 'emoji': emoji, 'name': name, 'desc': desc})

# categories were remapped at runtime — apply the same remap here
RECAT = {'percentage': 'math', 'num-to-words': 'math', 'roman': 'math', 'loan': 'finance',
         'tip': 'finance', 'discount': 'finance', 'bmi': 'health', 'timestamp': 'time',
         'age': 'time', 'date-diff': 'time'}
manifest = json.load(io.open(os.path.join(ROOT, 'tools.json'), encoding='utf-8'))
CATEGORIES = manifest['categories']
SLUGS = manifest['slugOverrides']

STOP = set('a an the to and or of in on for with from your you into more than'.split())
for t in tools:
    t['cat'] = RECAT.get(t['id'], t['cat'])
    t['slug'] = SLUGS.get(t['id'], t['id'])
    words = re.findall(r"[a-z0-9]+", t['name'].lower())
    kws = [w for w in words if w not in STOP]
    catname = CATEGORIES[t['cat']]['name'].lower()
    t['keywords'] = list(dict.fromkeys(kws + [t['name'].lower(), 'online tool', 'free', catname]))

assert len(tools) == len({t['id'] for t in tools}), 'duplicate ids!'
assert len(tools) == len({t['slug'] for t in tools}), 'duplicate slugs!'
for t in tools:
    assert t['cat'] in CATEGORIES, 'unknown cat ' + t['cat']

# ---- 4. Emit lib/catalog.js ----------------------------------------------
def js(v):
    return json.dumps(v, ensure_ascii=False)

lines = []
lines.append("/* AUTO-GENERATED by gen.py — server-safe tool catalog (no DOM). */")
lines.append("export const SITE = { name: 'UtilityHub', url: process.env.NEXT_PUBLIC_SITE_URL || 'https://utilitywebapps.vercel.app', tagline: 'Every little tool, all in one place.' };")
lines.append("export const CATEGORIES = " + js(CATEGORIES) + ";")
lines.append("export const CATEGORY_ORDER = " + js(list(CATEGORIES.keys())) + ";")
lines.append("export const TOOLS = [")
for t in tools:
    lines.append("  " + js({'id': t['id'], 'slug': t['slug'], 'cat': t['cat'], 'emoji': t['emoji'],
                            'name': t['name'], 'desc': t['desc'], 'keywords': t['keywords']}) + ",")
lines.append("];")
lines.append("export const bySlug = Object.fromEntries(TOOLS.map(t => [t.slug, t]));")
lines.append("export const byId = Object.fromEntries(TOOLS.map(t => [t.id, t]));")
lines.append("export const toolsByCat = (c) => TOOLS.filter(t => t.cat === c);")
lines.append("""export function seoTitle(t){ const base = t.name + ' \\u2013 Free Online Tool'; return base.length <= 60 ? base : (t.name + ' \\u2013 UtilityHub'); }""")
lines.append("""export function seoDescription(t){ const d = t.desc.replace(/\\s+$/, '').replace(/[.]$/, ''); const s = d + ' \\u2014 free, fast and 100% private, right in your browser. No signup, no uploads.'; return s.length <= 160 ? s : t.desc; }""")
io.open(os.path.join(ROOT, 'lib', 'catalog.js'), 'w', encoding='utf-8').write("\n".join(lines) + "\n")

print('tools:', len(tools))
print('categories:', len(CATEGORIES))
from collections import Counter
print('by cat:', dict(Counter(t['cat'] for t in tools)))
print('css bytes:', len(css), ' runtime bytes:', len(runtime))
print('sample slugs:', [t['slug'] for t in tools[:6]])
